### ISSUE TITLE
Unable to install on v3.0.2

### ISSUE THREAD

**Issue by Travelfrog** [Advanced-Ad-Management/Advanced-Ad-Management#10]
I have been unable to install on v3.0.2 as the zip file will not install. I get the following error.

There was a problem adding the plugin.

**Comment by mivilleb** [comment]
Exact same problem here. Version 1.1 of the advanced ad management does not install on OSClass v3.0.2.

"There was a problem adding the plugin"

Why version 1.1 is not listed under the OSClass Market?

**Comment by trains58554** [comment]
version 2.1 installs and works on 3.0.2

**Comment by beberon** [comment]
where is this version ?
